<a href="https://colab.research.google.com/github/thiaguera44/PythonPanda/blob/main/Primeiro_Exemplo_em_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Python Pandas**

Data: 06 de Favereiro de 2023

In [1]:
#Importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_excel("precos.xlsx")

In [2]:
print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [3]:
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [4]:
print(combustiveis_df.head)

<bound method NDFrame.head of        Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]>

In [5]:
display(combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [6]:
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [7]:
# Comandos DF.shape e DF.describe()
print(combustiveis_df.shape)
print(combustiveis_df.describe())

(168409, 16)
       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [8]:
display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [9]:
#Novo DF com colunas desejadas...
ca_df = combustiveis_df[['Revenda', 'Municipio','Produto', 'Valor de Venda']]
display(ca_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [10]:
print(ca_df.loc[9::19])

                                          Revenda        Municipio  \
9                  AUTO POSTO FREITAS & MAIA LTDA  DELMIRO GOUVEIA
28                            NOBRE E BRAGA LTDA.      ITACOATIARA
47                       POSTO ATLANTICO SUL LTDA           ILHEUS
66               MP COMERCIO DE COMBUSTIVEIS LTDA         SALVADOR
85                          POSTO KALILANDIA LTDA         SALVADOR
...                                           ...              ...
168330  AUTO POSTO SIQUELERO DE ITAPETININGA LTDA     ITAPETININGA
168349                       POSTO EXPOPEC EIRELI        ITUIUTABA
168368    AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA           JEQUIE
168387                    AUTO POSTO RAIDEN LTDA.            BAURU
168406          ABC DISTRIBUICAO DE PETROLEO LTDA        ITUIUTABA

           Produto  Valor de Venda
9       DIESEL S10           5.983
28          DIESEL           5.450
47          ETANOL           5.799
66        GASOLINA           6.630
85          ETANOL           5.670
...            ...             ...
168330      DIESEL           5.059
168349      DIESEL           5.458
168368      ETANOL           5.859
168387  DIESEL S10           5.199
168406      ETANOL           4.740

[8864 rows x 4 columns]

In [11]:
# Criando DF gas_df contendo apenas 4 colunas
# (Revenda, Municipio, Produto, Valor de Venda)
# somente com combustivel sendo Gasolina

gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA,7.198
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990
...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,GASOLINA,6.199
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,GASOLINA,6.899
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,7.090
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,GASOLINA,6.799
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580

7.999

In [12]:
# Qual o posto e municipio mais caro do país?

display(gas_df[['Revenda','Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object

In [26]:
#DataFrame.loc[] com múltiplas condições para filtragens
#Quais os preços, postos que vendem ETANOL na minha cidade (BELO HORIZONTE)

bh_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'BELO HORIZONTE')] 
bh_df.sort_values(by = 'Valor de Venda', inplace = True)
display(bh_df)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,Revenda,Municipio,Produto,Valor de Venda
144994,POSTO GALL LTDA,BELO HORIZONTE,ETANOL,5.098
164146,POSTO BOM BOM LTDA,BELO HORIZONTE,ETANOL,5.259
164116,CENTRO COMERCIAL DE COMBUSTIVEIS MINAS PALMARE...,BELO HORIZONTE,ETANOL,5.260
125936,POSTO ZEPPE JARDIM LTDA,BELO HORIZONTE,ETANOL,5.265
135386,POSTO ZEPPE JARDIM LTDA,BELO HORIZONTE,ETANOL,5.265
...,...,...,...,...
50264,POSTO CACHOEIRINHA LTDA.,BELO HORIZONTE,ETANOL,5.599
128965,POSTO BRUNATA LTDA,BELO HORIZONTE,ETANOL,5.599
31274,POSTO MARTE LTDA,BELO HORIZONTE,ETANOL,5.599
31237,POSTO PHOENIX LTDA,BELO HORIZONTE,ETANOL,5.635
69742,POSTO BH LTDA,BELO HORIZONTE,ETANOL,5.742

In [46]:
#Qual a média de preços dos combustiveis GASOLINA E GASOLINA ADITIVADA do Bairro BELA VISTA em SÃO PAULO?

display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') &
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [63]:
# Mostrar média de valor de venda POR COMBUSTIVEL do brasilzão todo?

media_combustivel_df = ca_df[['Produto','Valor de Venda']].groupby(by = 'Produto').mean().round(3)
display(media_combustivel_df)

                    Valor de Venda
Produto
DIESEL                       5.376
DIESEL S10                   5.455
ETANOL                       5.456
GASOLINA                     6.709
GASOLINA ADITIVADA           6.860
GNV                          4.393

In [65]:
#Quero adicionar uma coluna de valor booleano chamada "Ativo"
# que, por padrão, vai ser True para TODAS as linhas

combustiveis_df['Ativo'] = True 

print(combustiveis_df.shape)
print(combustiveis_df.info())

(168409, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

In [67]:
# Vou colocar uma coluna chamada "OBS"
# que preencha automaticamente "MELHOR CIDADE"
# quando o municipio for BELO HORIZONTE, MG...

#combustiveis_df['Obs'] = "MELHOR CIDADE" if combustiveis_df['Municipio'] == 'BELO HORIZONTE' else ""

In [68]:
#Exportar para Excel o DATAFRAME o Etanol em Belo Horizonte

bh_df.to_excel('etanol_bh.xlsx', sheet_name = 'Etanol em Belo Horizonte')